name: Build Plugin Zip File

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Create build archive
      run: |
        mkdir -p wp2static-addon-github
        rsync -r \
          --include="/*.php" \
          --include="/admin/" \
          --include="/admin/**" \
          --include="/includes/" \
          --include="/includes/**" \
          --include="/views/" \
          --include="/views/**" \
          --exclude="*" \
          ./ wp2static-addon-github/
        zip --quiet -r -9 wp2static-addon-github.zip wp2static-addon-github
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: wp2static-addon-github
        path: wp2static-addon-github.zip
        retention-days: 90